### ISSUE TITLE
Stopping game mode doesn't loads again any scene

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#42]
## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Put a scene with some game objects
 
 2. Press play, then stop
 
 3. It loads an empty scene

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Stopping the game mode should load the previous scene (saved when clicked play)

### Actual result:
It doesn't loads ANY scene

## Build
- **Please specify the build:** ``Insert the build here`` 1.8

**Comment by ch0m5** [comment]
Aitor, I found more details about this issue that you can find in my own called **"Save & Load of "Play" not working as intended".** This problem is rooted in the load being made on the Saved Scene, instead of the temporal one created when pressing PLAY. If there no Saved Scene, the load fails I suppose.

**Comment by AitorSimona** [comment]
Bug introduced in a previous merge, now solved
