### ISSUE TITLE
Save & Load of GOs with Scripts breaks them

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#47]
## Bug Description
Playing a Scene with Scripts, loading the Scene back, and playing it again will result in a very weird behavior from those same GOs with scripts.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Save a Scene with GeraltScript and CameraScript in their correspondent GOs
 
 2. PLAY, STOP, PLAY
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Script runs again as before.

### Actual result:
Script goes insane, GO fly to kingdom come, and massive values are logged to console.

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36209557/76342291-a94f8e80-62fe-11ea-9c22-e9dba8418356.png)

## Build
Broken Engine 2.0

## Observations and Additional Information
I didn't bother to test or replicate this bug with different scripts or environments, it's something I found while testing Geralt. If you want more details contact me personally - Carles

**Comment by DidacRomero** [comment]
Hi @ch0m5 I have fixed a bug that caused the engine to NOT update script variables with teh editor value after Runing for the first time (meaning after a load and save, the script dind't update its values with the editor values). Further testing is required with the said scripts, since I don't know the full setup of the scene, but it is highly probable this fix fixed the issue. Please remind me about testing whenever we finish the delivery of the VS.

**Comment by DidacRomero** [comment]
Upon the various changes and fixes on thye last builds this issue has been solved, this issue will now be closed.
